DROP TABLE IF EXISTS USER_INFO;

CREATE TABLE PUBLIC.TBL_DATASET_INFO (
	ID INT8 NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USER_ID VARCHAR(100) NOT NULL,
	USER_NAME VARCHAR(255) NULL,
	SEX INT8 NULL DEFAULT 0
);
